<?php

namespace AppBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPublicatedOnes()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Annonce a '
                . 'WHERE a.datePublication <= CURRENT_TIMESTAMP()'
                . 'ORDER BY a.datePublication DESC'
            )
            ->setMaxResults(10)->getResult();
    }
}
