<?php

namespace AppBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{

    public function findComingOnes()
    {
        return $this->getEntityManager()
                ->createQuery(
                    'SELECT e FROM AppBundle:Evenement e '
                    . 'WHERE e.dateDebut >= CURRENT_TIMESTAMP() '
                    . 'ORDER BY e.dateDebut ASC '
                )
                ->setMaxResults(10)->getResult();
    }

    public function findPublicOnes()
    {
        return $this->getEntityManager()
                ->createQuery(
                    'SELECT e FROM AppBundle:Evenement e '
                    . 'WHERE e.estPublic = true '
                )
                ->getResult();
    }

    public function findComingAndPublicOnes()
    {
        return $this->getEntityManager()
                ->createQuery(
                    'SELECT e FROM AppBundle:Evenement e '
                    . 'WHERE e.dateDebut >= CURRENT_TIMESTAMP() '
                    . 'AND e.estPublic = true '
                    . 'ORDER BY e.dateDebut ASC '
                )
                ->setMaxResults(10)->getResult();
    }

}
