<?php

namespace AppBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatest()
    {
        return $this->getEntityManager()
                ->createQuery(
                    'SELECT n FROM AppBundle:Notification n '
                    . 'ORDER BY n.dateCreation ASC'
                )
                ->setMaxResults(10)->getResult();
    }
}