<?php

namespace AppBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function utilisateurExiste($login)
    {
        return $this->createQueryBuilder('u')
            ->where('u.pseudo = :pseudo OR u.mail = :mail')
            ->setParameter('pseudo', $login)
            ->setParameter('mail', $login)
            ->getQuery()
            ->getOneOrNullResult();
    }
}